# Generated by Django 5.2.15 on 2026-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0003_remove_staff_cohort_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
