# Generated by Django 5.2.15 on 2026-08-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0060_calloutelement_numbered"),
        ("grouping", "0004_group_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("archived", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "cohorts",
                    models.ManyToManyField(
                        blank=True, related_name="allocations", to="grouping.cohort"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="grouping.allocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                fields=("course", "name"), name="uniq_allocation_course_name"
            ),
        ),
    ]
