import datetime

from django.core import mail
from django.utils import timezone

from accounts.invitations import INVITE_SUBJECT
from accounts.invitations import build_accept_url
from accounts.invitations import send_invitation_email
from accounts.models import INVITE_TTL
from accounts.models import Invitation
from accounts.models import User
from tests.factories import TEST_PASSWORD


def test_token_is_autogenerated_and_unique():
    a = Invitation.objects.create(email="a@school.edu")
    b = Invitation.objects.create(email="b@school.edu")
    assert a.token and b.token and a.token != b.token


def test_expires_at_defaults_to_now_plus_ttl():
    before = timezone.now()
    inv = Invitation.objects.create(email="a@school.edu")
    assert inv.expires_at >= before + INVITE_TTL - datetime.timedelta(seconds=5)
    assert inv.expires_at <= timezone.now() + INVITE_TTL + datetime.timedelta(seconds=5)


def test_is_valid_true_when_fresh():
    inv = Invitation.objects.create(email="a@school.edu")
    assert inv.is_valid()


def test_is_valid_false_when_expired():
    inv = Invitation.objects.create(
        email="a@school.edu", expires_at=timezone.now() - datetime.timedelta(days=1)
    )
    assert not inv.is_valid()


def test_is_valid_false_when_accepted():
    inv = Invitation.objects.create(email="a@school.edu", accepted_at=timezone.now())
    assert not inv.is_valid()


def test_status_string_precedence():
    accepted = Invitation.objects.create(
        email="a@school.edu", accepted_at=timezone.now()
    )
    expired = Invitation.objects.create(
        email="b@school.edu", expires_at=timezone.now() - datetime.timedelta(days=1)
    )
    pending = Invitation.objects.create(email="c@school.edu")
    assert accepted.status == "accepted"
    assert expired.status == "expired"
    assert pending.status == "pending"
    assert str(pending) == "c@school.edu (pending)"


def _make_invite(email="invitee@school.edu", **kwargs):
    return Invitation.objects.create(email=email, **kwargs)


def test_accept_get_renders_form_with_email(client):
    inv = _make_invite()
    response = client.get(f"/invite/accept/{inv.token}/")
    assert response.status_code == 200
    assert b"invitee@school.edu" in response.content


def test_accept_valid_creates_student_logged_in(client):
    inv = _make_invite()
    response = client.post(
        f"/invite/accept/{inv.token}/",
        {"username": "invitee", "password": TEST_PASSWORD},
    )
    assert response.status_code == 302
    assert response["Location"].endswith(
        "/home/"
    )  # LOGIN_REDIRECT_URL resolves to /home/
    user = User.objects.get(username="invitee")
    assert user.groups.filter(name="Student").exists()
    from allauth.account.models import EmailAddress

    assert EmailAddress.objects.filter(
        user=user, email="invitee@school.edu", verified=True, primary=True
    ).exists()
    inv.refresh_from_db()
    assert inv.accepted_at is not None  # token consumed
    assert client.session.get("_auth_user_id")  # logged in


def test_accept_unknown_token_shows_invalid(client):
    response = client.get("/invite/accept/not-a-real-token/")
    assert response.status_code == 200
    assert b"invalid or has expired" in response.content  # invalid page, not the form
    assert not User.objects.filter(username="invitee").exists()


def test_accept_expired_token_shows_invalid_no_account(client):
    inv = _make_invite(expires_at=timezone.now() - datetime.timedelta(days=1))
    response = client.post(
        f"/invite/accept/{inv.token}/",
        {"username": "invitee", "password": TEST_PASSWORD},
    )
    assert response.status_code == 200  # invalid page, not a redirect
    assert not User.objects.filter(username="invitee").exists()


def test_accept_used_token_cannot_be_reused(client):
    inv = _make_invite()
    client.post(
        f"/invite/accept/{inv.token}/",
        {"username": "invitee", "password": TEST_PASSWORD},
    )
    client.logout()
    response = client.post(
        f"/invite/accept/{inv.token}/",
        {"username": "invitee2", "password": TEST_PASSWORD},
    )
    assert response.status_code == 200  # invalid page
    assert not User.objects.filter(username="invitee2").exists()


def test_accept_email_already_registered_shows_invalid(client):
    from tests.factories import make_verified_user

    make_verified_user(username="existing", email="invitee@school.edu")
    inv = _make_invite(email="invitee@school.edu")
    response = client.get(f"/invite/accept/{inv.token}/")
    assert response.status_code == 200
    assert b"log in" in response.content.lower()
    assert (
        User.objects.count() == 1
    )  # only the pre-seeded "existing" user; none created


def test_accept_when_authenticated_redirects_without_consuming(client):
    from tests.factories import make_verified_user

    member = make_verified_user(username="member", email="member@school.edu")
    client.force_login(member)
    inv = _make_invite()
    response = client.get(f"/invite/accept/{inv.token}/")
    assert response.status_code == 302
    assert response["Location"].endswith("/home/")
    inv.refresh_from_db()
    assert inv.accepted_at is None  # an already-logged-in user consumes nothing


def test_accept_taken_username_rerenders_form_token_unconsumed(client):
    from tests.factories import make_verified_user

    make_verified_user(username="taken", email="someone@school.edu")
    inv = _make_invite()
    response = client.post(
        f"/invite/accept/{inv.token}/",
        {"username": "taken", "password": TEST_PASSWORD},
    )
    assert response.status_code == 200  # form re-rendered with errors
    inv.refresh_from_db()
    assert inv.accepted_at is None  # token not consumed


def test_build_accept_url_contains_path_and_token():
    inv = _make_invite()
    url = build_accept_url(inv)
    assert f"/invite/accept/{inv.token}/" in url


def test_send_invitation_email_sends_one_plaintext_message():
    inv = _make_invite(email="newperson@school.edu")
    mail.outbox.clear()
    send_invitation_email(inv)
    assert len(mail.outbox) == 1
    message = mail.outbox[0]
    assert message.subject == INVITE_SUBJECT
    assert "newperson@school.edu" in message.to
    # Body carries the accept link (path + token); host is example.com in tests.
    assert f"/invite/accept/{inv.token}/" in message.body


def test_creating_invitation_sends_email_on_commit(
    django_capture_on_commit_callbacks,
):
    mail.outbox.clear()
    with django_capture_on_commit_callbacks(execute=True):
        inv = Invitation.objects.create(email="hook@school.edu")
    assert len(mail.outbox) == 1
    assert "hook@school.edu" in mail.outbox[0].to
    assert f"/invite/accept/{inv.token}/" in mail.outbox[0].body
