import pytest
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.db import transaction

from tests.factories import CohortFactory
from tests.factories import CollectionFactory
from tests.factories import CourseFactory
from tests.factories import GroupFactory
from tests.factories import GroupMembershipFactory
from tests.factories import UserFactory

pytestmark = pytest.mark.django_db


def test_slug_autogenerated_from_name():
    c = CohortFactory(name="Year 7")
    assert c.slug == "year-7"


def test_slug_suffixes_on_collision():
    CohortFactory(name="Year 7")
    c2 = CohortFactory(name="Year 7")
    assert c2.slug == "year-7-2"


def test_non_default_cohort_named_default_is_suffixed():
    c = CohortFactory(name="Default")  # not is_default
    assert c.slug == "default-2"


def test_at_most_one_default_cohort_enforced_by_constraint():
    # The migration already provides one default cohort; trying to create
    # a second must raise IntegrityError.
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            CohortFactory(name="A", is_default=True)


def test_groupmembership_unique_group_student():
    gm = GroupMembershipFactory()
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            GroupMembershipFactory(group=gm.group, student=gm.student)


def test_cohortmembership_is_one_to_one():
    from grouping.models import CohortMembership

    # Boundary-safe across Task 2: update_or_create guarantees exactly one row
    # whether or not the Default-cohort signal already created one. A second raw
    # create for the same user must then violate the OneToOne.
    user = UserFactory()
    CohortMembership.objects.update_or_create(
        user=user, defaults={"cohort": CohortFactory()}
    )
    assert CohortMembership.objects.filter(user=user).count() == 1
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            CohortMembership.objects.create(user=user, cohort=CohortFactory())


def test_group_course_is_immutable_after_create():
    g = GroupFactory()
    other = CourseFactory()
    g.course = other
    with pytest.raises(ValidationError):
        g.save()


def test_collection_course_immutable_only_when_groups_attached():
    coll = CollectionFactory()
    other = CourseFactory()
    # No groups attached yet -> retarget is allowed.
    coll.course = other
    coll.save()  # no error
    # Attach a group on the new course, then retargeting is blocked.
    g = GroupFactory(course=other)
    coll.groups.add(g)
    coll.course = CourseFactory()
    with pytest.raises(ValidationError):
        coll.save()
