import datetime

from django.utils import timezone

from accounts.models import INVITE_TTL
from accounts.models import Invitation


def test_token_is_autogenerated_and_unique():
    a = Invitation.objects.create(email="a@school.edu")
    b = Invitation.objects.create(email="b@school.edu")
    assert a.token and b.token and a.token != b.token


def test_expires_at_defaults_to_now_plus_ttl():
    before = timezone.now()
    inv = Invitation.objects.create(email="a@school.edu")
    assert inv.expires_at >= before + INVITE_TTL - datetime.timedelta(seconds=5)
    assert inv.expires_at <= timezone.now() + INVITE_TTL + datetime.timedelta(seconds=5)


def test_is_valid_true_when_fresh():
    inv = Invitation.objects.create(email="a@school.edu")
    assert inv.is_valid()


def test_is_valid_false_when_expired():
    inv = Invitation.objects.create(
        email="a@school.edu", expires_at=timezone.now() - datetime.timedelta(days=1)
    )
    assert not inv.is_valid()


def test_is_valid_false_when_accepted():
    inv = Invitation.objects.create(email="a@school.edu", accepted_at=timezone.now())
    assert not inv.is_valid()


def test_status_string_precedence():
    accepted = Invitation.objects.create(
        email="a@school.edu", accepted_at=timezone.now()
    )
    expired = Invitation.objects.create(
        email="b@school.edu", expires_at=timezone.now() - datetime.timedelta(days=1)
    )
    pending = Invitation.objects.create(email="c@school.edu")
    assert accepted.status == "accepted"
    assert expired.status == "expired"
    assert pending.status == "pending"
    assert str(pending) == "c@school.edu (pending)"
