# Generated by Django 5.2.15 on 2026-06-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Course Admin', 'Course Admin'), ('Platform Admin', 'Platform Admin')], default='Student', help_text='Role the invitee lands in on accept.', max_length=32),
        ),
    ]
