# Generated by Django 5.2.15 on 2026-07-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='names_locked',
            field=models.BooleanField(default=False),
        ),
    ]
