# Generated by Django 5.2.15 on 2026-08-22 21:22

import django.db.models.deletion
import support.models
import support.storage
import support.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('admins', 'Platform Admins only'), ('course_admins', 'Course Admins and Platform Admins'), ('teachers', 'Teachers, Course Admins and Platform Admins'), ('all', 'Everyone, including students')], default='admins', max_length=16)),
                ('extra_emails', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_reporters', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_label', models.CharField(blank=True, max_length=200)),
                ('reporter_roles', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('page_url', models.TextField(blank=True)),
                ('page_title', models.CharField(blank=True, max_length=300)),
                ('screenshot', models.ImageField(blank=True, storage=support.storage.ScreenshotStorage, upload_to=support.models.screenshot_upload_to, validators=[support.validators.validate_screenshot_file])),
                ('telemetry', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='support_iss_status_f3d0e0_idx'), models.Index(fields=['reporter', '-created_at'], name='support_iss_reporte_d6a151_idx')],
            },
        ),
    ]
