# Generated by Django 5.2.15 on 2026-06-28 16:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0026_course_color_bands'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='courses.element')),
                ('unit', models.ForeignKey(limit_choices_to={'kind': 'unit'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.contentnode')),
            ],
            options={
                'ordering': ['created', 'pk'],
                'indexes': [models.Index(fields=['author', 'unit'], name='notes_note_author__e1953b_idx'), models.Index(fields=['author', 'element'], name='notes_note_author__b40055_idx')],
            },
        ),
    ]
