# Generated by Django 5.2.15 on 2026-06-15 11:42

import courses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('part', 'Part'), ('chapter', 'Chapter'), ('section', 'Section'), ('unit', 'Unit')], max_length=10)),
                ('order', courses.fields.OrderField(blank=True, for_fields=['course', 'parent'])),
                ('title', models.CharField(max_length=200)),
                ('unit_type', models.CharField(blank=True, choices=[('lesson', 'Lesson'), ('quiz', 'Quiz')], max_length=10, null=True)),
                ('obligatory', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='courses.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.contentnode')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
