# Generated by Django 5.2.15 on 2026-06-15 11:49

import courses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0002_contentnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', courses.fields.OrderField(blank=True, for_fields=['unit'])),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('unit', models.ForeignKey(limit_choices_to={'kind': 'unit'}, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='courses.contentnode')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
