# Generated by Django 5.2.15 on 2026-06-15 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_iframeelement_imageelement_mathelement_videoelement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('group', 'Group'), ('self', 'Self')], default='manual', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='uniq_enrollment_student_course')],
            },
        ),
        migrations.CreateModel(
            name='UnitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_element_ids', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_progress', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(limit_choices_to={'kind': 'unit'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.contentnode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'unit'), name='uniq_progress_student_unit')],
            },
        ),
    ]
