# Generated by Django 5.2.15 on 2026-06-15 13:15

import courses.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_unitprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='image',
            field=models.ImageField(upload_to='courses/images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp']), courses.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='file',
            field=models.FileField(blank=True, upload_to='courses/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov']), courses.validators.validate_video_size]),
        ),
    ]
