# Generated by Django 5.2.15 on 2026-06-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_migrate_files_to_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
