# Generated by Django 5.2.15 on 2026-06-18 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0009_mediaasset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contentnode',
            name='html_seed_js',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='html_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='html_js',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement', 'htmlelement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
