# Generated by Django 5.2.15 on 2026-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_html_seed_js_to_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
