# Generated by Django 5.2.15 on 2026-06-19 15:55

import courses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0012_element_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('multiple', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement', 'htmlelement', 'choicequestionelement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', courses.fields.OrderField(blank=True, for_fields=['question'])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.choicequestionelement')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
