# Generated by Django 5.2.15 on 2026-06-20 00:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_fillblankquestionelement_shortnumericquestionelement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestionelement',
            name='marking_mode',
            field=models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='choicequestionelement',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='choicequestionelement',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='fillblankquestionelement',
            name='marking_mode',
            field=models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='fillblankquestionelement',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='fillblankquestionelement',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='shortnumericquestionelement',
            name='marking_mode',
            field=models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='shortnumericquestionelement',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='shortnumericquestionelement',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='shorttextquestionelement',
            name='marking_mode',
            field=models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='shorttextquestionelement',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='shorttextquestionelement',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
