# Generated by Django 5.2.15 on 2026-06-20 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_question_marking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(limit_choices_to={'kind': 'unit'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to='courses.contentnode')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('latest_answer', models.JSONField(blank=True, null=True)),
                ('fraction', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('earned_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.element')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.quizsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveSmallIntegerField()),
                ('answer', models.JSONField()),
                ('fraction', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('correct', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.questionresponse')),
            ],
            options={
                'ordering': ['n'],
                'constraints': [models.UniqueConstraint(fields=('response', 'n'), name='uniq_attempt_response_n')],
            },
        ),
        migrations.AddConstraint(
            model_name='quizsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'unit'), name='uniq_quizsubmission_student_unit'),
        ),
        migrations.AddConstraint(
            model_name='questionresponse',
            constraint=models.UniqueConstraint(fields=('submission', 'element'), name='uniq_response_submission_element'),
        ),
    ]
