# Generated by Django 5.2.15 on 2026-06-20 20:47

import courses.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_quizsubmission_questionresponse_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragFillBlankQuestionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('marking_mode', models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('distractors', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchPairQuestionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('marking_mode', models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('distractors', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DragBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_token', models.CharField(max_length=500)),
                ('order', courses.fields.OrderField(blank=True, for_fields=['question'])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragblanks', to='courses.dragfillblankquestionelement')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(max_length=500)),
                ('right', models.CharField(max_length=500)),
                ('order', courses.fields.OrderField(blank=True, for_fields=['question'])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='courses.matchpairquestionelement')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
