# Generated by Django 5.2.15 on 2026-06-21 20:44

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models

import courses.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_dragfill_matchpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragToImageQuestionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('marking_mode', models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('distractors', models.TextField(blank=True)),
                ('media', models.ForeignKey(limit_choices_to={'kind': 'image'}, on_delete=django.db.models.deletion.PROTECT, to='courses.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DragZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_label', models.CharField(max_length=500)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('order', courses.fields.OrderField(blank=True, for_fields=['question'])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='courses.dragtoimagequestionelement')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
