# Generated by Django 5.2.15 on 2026-06-22 13:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_dragtoimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedResponseQuestionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('marking_mode', models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('required_keywords', models.TextField(blank=True)),
                ('forbidden_keywords', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
