# Generated by Django 5.2.15 on 2026-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_quizsubmission_submitted_by'),
        ('grouping', '0003_remove_staff_cohort_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='self_enroll_cohorts',
            field=models.ManyToManyField(blank=True, related_name='self_enroll_courses', to='grouping.cohort'),
        ),
    ]
