# Generated by Django 5.2.15 on 2026-06-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_self_enroll_cohorts'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='review_feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
