# Generated by Django 5.2.15 on 2026-06-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0025_course_subjects_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="color_bands",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
