# Generated by Django 5.2.15 on 2026-07-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0027_course_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement', 'htmlelement', 'choicequestionelement', 'shorttextquestionelement', 'extendedresponsequestionelement', 'shortnumericquestionelement', 'fillblankquestionelement', 'dragfillblankquestionelement', 'matchpairquestionelement', 'dragtoimagequestionelement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
