# Generated by Django 5.2.15 on 2026-07-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0031_mat_pp_theme_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideBreakElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement', 'htmlelement', 'choicequestionelement', 'shorttextquestionelement', 'extendedresponsequestionelement', 'shortnumericquestionelement', 'fillblankquestionelement', 'dragfillblankquestionelement', 'matchpairquestionelement', 'dragtoimagequestionelement', 'slidebreakelement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
