# Generated by Django 5.2.15 on 2026-07-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0034_galleryelement_alter_element_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabsElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='element',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.element'),
        ),
        migrations.AddField(
            model_name='element',
            name='tab_id',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement', 'htmlelement', 'choicequestionelement', 'shorttextquestionelement', 'extendedresponsequestionelement', 'shortnumericquestionelement', 'fillblankquestionelement', 'dragfillblankquestionelement', 'matchpairquestionelement', 'dragtoimagequestionelement', 'slidebreakelement', 'tableelement', 'galleryelement', 'tabselement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
