# Generated by Django 5.2.15 on 2026-07-14 10:11

import courses.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0042_calloutelement_alter_element_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceGridQuestionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('marking_mode', models.CharField(choices=[('A', 'Auto-marked'), ('N', 'Not marked'), ('R', 'Requires review')], default='A', max_length=1)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement', 'htmlelement', 'choicequestionelement', 'shorttextquestionelement', 'extendedresponsequestionelement', 'shortnumericquestionelement', 'fillblankquestionelement', 'dragfillblankquestionelement', 'matchpairquestionelement', 'dragtoimagequestionelement', 'slidebreakelement', 'tableelement', 'galleryelement', 'tabselement', 'revealgateelement', 'fillgateelement', 'switchgateelement', 'spoilerelement', 'switchgridelement', 'filltableelement', 'calloutelement', 'choicegridquestionelement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='GridColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('order', courses.fields.OrderField(blank=True, for_fields=['question'])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='courses.choicegridquestionelement')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GridRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=500)),
                ('order', courses.fields.OrderField(blank=True, for_fields=['question'])),
                ('correct_column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='courses.gridcolumn')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='courses.choicegridquestionelement')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
