# Generated by Django 5.2.15 on 2026-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_choicegridquestionelement_alter_element_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='feedback',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
