# Generated by Django 5.2.15 on 2026-07-14 19:44

import courses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0044_choice_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepperElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement', 'htmlelement', 'choicequestionelement', 'shorttextquestionelement', 'extendedresponsequestionelement', 'shortnumericquestionelement', 'fillblankquestionelement', 'dragfillblankquestionelement', 'matchpairquestionelement', 'dragtoimagequestionelement', 'slidebreakelement', 'tableelement', 'galleryelement', 'tabselement', 'revealgateelement', 'fillgateelement', 'switchgateelement', 'spoilerelement', 'switchgridelement', 'filltableelement', 'calloutelement', 'choicegridquestionelement', 'stepperelement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='StepperStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('order', courses.fields.OrderField(blank=True, for_fields=['stepper'])),
                ('stepper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.stepperelement')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
