# Generated by Django 5.2.15 on 2026-07-16 13:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0048_markdoneelement_unitprogress_checklist_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessNumberElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(blank=True)),
                ('target', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tolerance', models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('success_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'courses', 'model__in': ['textelement', 'imageelement', 'videoelement', 'iframeelement', 'mathelement', 'htmlelement', 'choicequestionelement', 'shorttextquestionelement', 'extendedresponsequestionelement', 'shortnumericquestionelement', 'fillblankquestionelement', 'dragfillblankquestionelement', 'matchpairquestionelement', 'dragtoimagequestionelement', 'slidebreakelement', 'tableelement', 'galleryelement', 'tabselement', 'revealgateelement', 'fillgateelement', 'switchgateelement', 'spoilerelement', 'switchgridelement', 'filltableelement', 'calloutelement', 'choicegridquestionelement', 'stepperelement', 'multigridquestionelement', 'twocolumnelement', 'markdoneelement', 'guessnumberelement']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
