# Generated by Django 5.2.15 on 2026-07-19 19:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0050_remove_unitprogress_checklist_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="content_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
