# Generated by Django 5.2.15 on 2026-08-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_mediaasset_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calloutelement',
            name='kind',
            field=models.CharField(choices=[('example', 'Example'), ('note', 'Note'), ('tip', 'Tip'), ('warning', 'Important')], default='example', max_length=12),
        ),
    ]
