# Generated by Django 5.2.15 on 2026-08-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_spoiler_body_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('full', 'Full')], default='full', max_length=8),
        ),
    ]
