# Generated by Django 5.2.15 on 2026-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_beforeafterelement_alter_element_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calloutelement',
            name='kind',
            field=models.CharField(choices=[('example', 'Example'), ('note', 'Note'), ('tip', 'Tip'), ('warning', 'Important'), ('task', 'Task')], default='example', max_length=12),
        ),
    ]
