# Generated by Django 5.2.15 on 2026-08-17 16:29
"""Schema-only: five AddField for the media-derivative pipeline.

No data migration. Populating the new fields for the ~953 existing mat-pp
images is the job of `backfill_media_derivatives`, which is resumable and
re-runnable; doing it here would make the migration long-running and
irreversible in practice. Fully reversible as written.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_shortnumeric_text_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='derivatives_state',
            field=models.CharField(blank=True, choices=[('ok', 'Generated'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='thumb',
            field=models.FileField(blank=True, max_length=200, upload_to='courses/media/derivatives/'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='web',
            field=models.FileField(blank=True, max_length=200, upload_to='courses/media/derivatives/'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
