# Generated by Django 5.2.15 on 2026-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_mediaasset_derivatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='calloutelement',
            name='numbered',
            field=models.BooleanField(default=True),
        ),
    ]
