# Generated by Django 5.2.15 on 2026-08-18 14:33

from django.db import migrations, models


def _unnumber_note_and_tip(apps, schema_editor):
    """Kinds whose per-kind default is False (spec D2/D5).

    The list is a FROZEN LITERAL copied from courses.models.KIND_DEFAULT_NUMBERED,
    deliberately NOT an import: a migration that reads a live module constant
    silently changes meaning the day that constant is edited.

    Historical model + bulk update: the live CalloutElement.save() re-sanitises
    `body`, and .update() never touches it.
    """
    Callout = apps.get_model("courses", "CalloutElement")
    Callout.objects.filter(kind__in=["note", "tip"]).update(numbered=False)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_mediaasset_derivatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='calloutelement',
            name='numbered',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(_unnumber_note_and_tip, migrations.RunPython.noop),
    ]
