# Generated by Django 5.2.15 on 2026-08-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_calloutelement_numbered'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
