# Generated by Django 5.2.15 on 2026-09-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_figcaption_richtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividerElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
