# Generated by Django 5.2.15 on 2026-09-25 12:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0066_blank_answers_unescape"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionresponse",
            name="revealed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
