# Generated by Django 5.2.15 on 2026-10-08 12:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0068_alter_calloutelement_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageelement",
            name="float_right",
            field=models.BooleanField(default=False),
        ),
    ]
