# Generated by Django 5.2.15 on 2026-06-28 23:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0026_course_color_bands'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('teal', 'teal'), ('amber', 'amber'), ('indigo', 'indigo'), ('rose', 'rose'), ('green', 'green'), ('violet', 'violet'), ('slate', 'slate'), ('cyan', 'cyan')], default='teal', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name'), 'pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_tags', to='tags.tag')),
                ('unit', models.ForeignKey(limit_choices_to={'kind': 'unit'}, on_delete=django.db.models.deletion.CASCADE, related_name='unit_tags', to='courses.contentnode')),
            ],
            options={
                'ordering': ['created', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='units',
            field=models.ManyToManyField(related_name='tags', through='tags.UnitTag', to='courses.contentnode'),
        ),
        migrations.AddIndex(
            model_name='unittag',
            index=models.Index(fields=['unit'], name='tags_unitta_unit_id_9cfd27_idx'),
        ),
        migrations.AddIndex(
            model_name='unittag',
            index=models.Index(fields=['tag'], name='tags_unitta_tag_id_de3295_idx'),
        ),
        migrations.AddConstraint(
            model_name='unittag',
            constraint=models.UniqueConstraint(models.F('tag'), models.F('unit'), name='uniq_unittag_tag_unit'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('author'), name='uniq_tag_author_lower_name'),
        ),
    ]
