# Generated by Django 5.2.15 on 2026-06-13 17:18

import django.db.models.deletion
import institution.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Institution', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('signup_policy', models.CharField(choices=[('invite', 'Invite only'), ('open', 'Open self-signup')], default='invite', max_length=10)),
                ('allowed_email_domains', models.JSONField(blank=True, default=list)),
                ('enabled_languages', models.JSONField(blank=True, default=institution.models.default_languages)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BrandColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40)),
                ('value', models.CharField(max_length=64)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_colors', to='institution.institution')),
            ],
            options={
                'unique_together': {('institution', 'key')},
            },
        ),
    ]
