# Generated by Django 5.2.15 on 2026-06-14 16:46

import institution.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcolor',
            name='value',
            field=models.CharField(max_length=64, validators=[institution.validators.validate_css_color]),
        ),
    ]
