# Generated by Django 5.2.15 on 2026-06-29 23:07

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_brandcolor_value_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='allowed_image_extensions',
            field=models.JSONField(blank=True, default=courses.validators.default_image_extensions),
        ),
        migrations.AddField(
            model_name='institution',
            name='allowed_video_extensions',
            field=models.JSONField(blank=True, default=courses.validators.default_video_extensions),
        ),
        migrations.AddField(
            model_name='institution',
            name='max_image_mib',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='institution',
            name='max_video_mib',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
