# Generated by Django 5.2.15 on 2026-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_institution_allowed_image_extensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='onboarded',
            field=models.BooleanField(default=False, help_text='Set True once the first-run setup wizard is completed.'),
        ),
    ]
