# Generated by Django 5.2.15 on 2026-07-03 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_institution_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='notification_retention_days',
            field=models.PositiveIntegerField(default=90, help_text='Delete read notifications older than this many days, measured from when each notification was created. 0 keeps read notifications indefinitely; orphaned notifications are removed regardless.', validators=[django.core.validators.MaxValueValidator(3650)]),
        ),
    ]
