# Generated by Django 5.2.15 on 2026-07-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_institution_notification_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Square PNG, 192-512 px, up to 256 KB. Replaces the libli icon in browser tabs and on home screens. Transparent areas show as black on iOS home screens - use a solid background for best results.', null=True, upload_to='branding/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo'),
        ),
    ]
