# Generated by Django 5.2.15 on 2026-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_institution_favicon_alter_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=5, verbose_name='Default theme'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(default='My Institution', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='signup_policy',
            field=models.CharField(choices=[('invite', 'Invite only'), ('open', 'Open self-signup')], default='invite', max_length=10, verbose_name='Signup policy'),
        ),
    ]
