# Generated by Django 5.2.15 on 2026-08-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_alter_institution_default_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact address for data requests'),
        ),
        migrations.AddField(
            model_name='institution',
            name='controller_address',
            field=models.TextField(blank=True, help_text='Postal address. Omitted from the notice entirely when blank.', verbose_name='Data controller address'),
        ),
        migrations.AddField(
            model_name='institution',
            name='controller_name',
            field=models.CharField(blank=True, help_text='Shown on the public privacy notice. Falls back to the institution name when blank.', max_length=200, verbose_name='Data controller name'),
        ),
        migrations.AddField(
            model_name='institution',
            name='demo_instance',
            field=models.BooleanField(default=False, help_text='Adds a warning to the public pages telling visitors not to enter real pupil data.', verbose_name='This is a demonstration site'),
        ),
        migrations.AddField(
            model_name='institution',
            name='supervisory_authority',
            field=models.CharField(blank=True, help_text='The data-protection regulator for your country (in Poland, UODO). A neutral phrase is used when blank.', max_length=200, verbose_name='Supervisory authority'),
        ),
        migrations.CreateModel(
            name='PublicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32)),
                ('language', models.CharField(max_length=5)),
                ('body_markdown', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug', 'language'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'language'), name='uniq_publicpage_slug_language')],
            },
        ),
    ]
