# Generated by Django 5.2.15 on 2026-09-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_institution_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='signup_policy',
            field=models.CharField(choices=[('invite', 'Invite only'), ('sso_only', 'SSO only'), ('open', 'Open self-signup')], default='invite', help_text='Invite only: you create every account. SSO only: anyone signing in through your identity provider gets an account automatically, with no password form on the site. Open self-signup: anyone can register with a password. SSO only and Open are both restricted by the allowed email domains below. Invitations and existing logins keep working whichever you choose.', max_length=10, verbose_name='Signup policy'),
        ),
    ]
