# Generated by Django 5.2.15 on 2026-09-07 08:00

from django.db import migrations, models


def seed_plans(apps, schema_editor):
    """Three structural placeholder bands, priceless.

    get_or_create, never update_or_create: a re-run must never overwrite a
    school's edited prices. defaults= is MANDATORY -- five fields are
    non-nullable with no default, so a bare get_or_create(order=N) raises
    IntegrityError on a fresh database.
    """
    PricingPlan = apps.get_model('institution', 'PricingPlan')
    for order, lo, hi, hours, courses, video in (
        (1, 1, 150, 6, 3, 10),
        (2, 151, 400, 8, 6, 20),
        (3, 401, 800, 12, 12, 40),
    ):
        PricingPlan.objects.get_or_create(
            order=order,
            defaults={
                'pupils_min': lo,
                'pupils_max': hi,
                'annual_price': None,
                'support_hours_per_term': hours,
                'courses_included': courses,
                'video_hours_included': video,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_alter_institution_signup_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='currency',
            field=models.CharField(default='PLN', help_text='ISO 4217 code, shown in the price column header.', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='institution',
            name='storage_allowance_gb',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to omit the allowance sentence from the page.', null=True, verbose_name='Storage allowance (GB)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='vat_note_en',
            field=models.TextField(blank=True, default='', verbose_name='VAT note (English)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='vat_note_pl',
            field=models.TextField(blank=True, default='', verbose_name='VAT note (Polish)'),
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('pupils_min', models.PositiveIntegerField()),
                ('pupils_max', models.PositiveIntegerField()),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('support_hours_per_term', models.PositiveSmallIntegerField()),
                ('courses_included', models.PositiveSmallIntegerField()),
                ('video_hours_included', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('pupils_min__lt', models.F('pupils_max'))), name='pricingplan_band_is_ordered')],
            },
        ),
        migrations.RunPython(seed_plans, migrations.RunPython.noop),
    ]
